/// Flutter icons Champions
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Champions
///      fonts:
///       - asset: fonts/Champions.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Champions {
  Champions._();

  static const _kFontFam = 'Champions';

  static const IconData trophy = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData award = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData award_empty = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData award_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData award_2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData trophy_1 = const IconData(0xf074, fontFamily: _kFontFam);
}
